framework:
    http_client:
        scoped_clients:
            gotenberg.client:
                base_uri: '%env(GOTENBERG_DSN)%'

sensiolabs_gotenberg:
    http_client: 'gotenberg.client'
    default_options:
        pdf:
            html:
                footer:
                    template: 'footer.html.twig'
                paper_width: '21cm'
                paper_height: '29.7cm'
                margin_top: '6cm'
                margin_bottom: '2cm'
                landscape: true
