framework:
    http_client:
        scoped_clients:
            gotenberg.client:
                base_uri: '%env(GOTENBERG_DSN)%'

sensiolabs_gotenberg:
    http_client: 'gotenberg.client'
    default_options:
        pdf:
            html:
                footer:
                    template: 'footer.html.twig'
                paper_width: 8.27
                paper_height: 11.7
                margin_top: 2.4
                margin_bottom: 0.8
                landscape: true
